---
- name: Deploy Spring Boot Application
  hosts: seed-hosts
  vars:
    application_name: sample-spring-boot-rest-app
    ci_cd_namespace: sandbox-pd-ci-cd
    dev_namespace: sandbox-pd-dev
    test_namespace: sandbox-pd-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
